// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using api_my_bank_dotnet.Data;

namespace api_my_bank_dotnet.Migrations
{
  [DbContext(typeof(DataContext))]
  [Migration("20220114115720_conta_bancaria")]
  partial class conta_bancaria
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
        .HasAnnotation("Relational:MaxIdentifierLength", 64)
        .HasAnnotation("ProductVersion", "5.0.13");

      modelBuilder.Entity("api_my_bank_dotnet.Entities.ContaBancaria", b =>
      {
        b.Property<ulong>("conta_bancaria_id")
          .ValueGeneratedOnAdd()
          .HasColumnType("bigint unsigned");

        b.Property<DateTime>("created_at")
          .HasColumnType("datetime");

        b.Property<uint>("num_agencia")
          .HasColumnType("int unsigned");

        b.Property<ulong>("num_conta_corrente")
          .HasColumnType("bigint unsigned");

        b.HasKey("conta_bancaria_id");

        b.HasIndex("num_conta_corrente")
          .IsUnique();

        b.ToTable("conta_bancaria");
      });
#pragma warning restore 612, 618
    }
  }
}