// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_my_bank_dotnet.Entities;

namespace api_my_bank_dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220114120717_usuario")]
    partial class usuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("api_my_bank_dotnet.Entities.ContaBancaria", b =>
                {
                    b.Property<ulong>("conta_bancaria_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<uint>("num_agencia")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("num_conta_corrente")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("conta_bancaria_id");

                    b.HasIndex("num_conta_corrente")
                        .IsUnique();

                    b.ToTable("conta_bancaria");
                });

            modelBuilder.Entity("api_my_bank_dotnet.Entities.Endereco", b =>
                {
                    b.Property<ulong>("endereco_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("complemento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("logradouro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime");

                    b.HasKey("endereco_id");

                    b.ToTable("endereco");
                });

            modelBuilder.Entity("api_my_bank_dotnet.Entities.Usuario", b =>
                {
                    b.Property<ulong>("usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("apelido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<ulong>("conta_bancaria_id")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("data_nascimento")
                        .HasColumnType("date");

                    b.Property<ulong>("endereco_id")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("estado_civil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("nome_completo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<ulong>("renda_mensal")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("rg")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime");

                    b.HasKey("usuario_id");

                    b.HasIndex("conta_bancaria_id")
                        .IsUnique();

                    b.HasIndex("endereco_id")
                        .IsUnique();

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("api_my_bank_dotnet.Entities.Usuario", b =>
                {
                    b.HasOne("api_my_bank_dotnet.Entities.ContaBancaria", "contaBancaria")
                        .WithOne("usuario")
                        .HasForeignKey("api_my_bank_dotnet.Entities.Usuario", "conta_bancaria_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_my_bank_dotnet.Entities.Endereco", "endereco")
                        .WithOne("usuario")
                        .HasForeignKey("api_my_bank_dotnet.Entities.Usuario", "endereco_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("contaBancaria");

                    b.Navigation("endereco");
                });

            modelBuilder.Entity("api_my_bank_dotnet.Entities.ContaBancaria", b =>
                {
                    b.Navigation("usuario");
                });

            modelBuilder.Entity("api_my_bank_dotnet.Entities.Endereco", b =>
                {
                    b.Navigation("usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
