// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using api_my_bank_dotnet.Data;

namespace api_my_bank_dotnet.Migrations
{
  [DbContext(typeof(DataContext))]
  [Migration("20220114141043_address")]
  partial class address
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
        .HasAnnotation("Relational:MaxIdentifierLength", 64)
        .HasAnnotation("ProductVersion", "5.0.13");

      modelBuilder.Entity("api_my_bank_dotnet.Models.Address", b =>
      {
        b.Property<ulong>("address_id")
          .ValueGeneratedOnAdd()
          .HasColumnType("bigint unsigned");

        b.Property<ulong>("user_id")
         .HasColumnType("bigint unsigned");

        b.Property<string>("address_name")
          .IsRequired()
          .HasMaxLength(255)
          .HasColumnType("varchar(255)");

        b.Property<string>("number")
          .IsRequired()
          .HasMaxLength(20)
          .HasColumnType("varchar(20)");

        b.Property<string>("complement")
          .IsRequired()
          .HasMaxLength(255)
          .HasColumnType("varchar(255)");

        b.Property<string>("district")
          .IsRequired()
          .HasMaxLength(255)
          .HasColumnType("varchar(255)");

        b.Property<string>("city")
          .IsRequired()
          .HasMaxLength(255)
          .HasColumnType("varchar(255)");

        b.Property<string>("state")
          .IsRequired()
          .HasMaxLength(255)
          .HasColumnType("varchar(255)");

        b.Property<string>("country")
          .IsRequired()
          .HasMaxLength(255)
          .HasColumnType("varchar(255)");

        b.Property<DateTime>("created_at")
          .HasColumnType("datetime");

        b.Property<DateTime>("updated_at")
          .HasColumnType("datetime");

        b.HasKey("address_id");

        b.HasIndex("user_id");

        b.ToTable("address");
      });

      modelBuilder.Entity("api_my_bank_dotnet.Models.Address", b =>
      {
        b.HasOne("api_my_bank_dotnet.Models.User", "user")
          .WithOne("addresses")
          .HasForeignKey("api_my_bank_dotnet.Models.User", "bank_account_id")
          .OnDelete(DeleteBehavior.Cascade)
          .IsRequired();

        b.Navigation("user");
      });

      modelBuilder.Entity("api_my_bank_dotnet.Models.User", b =>
      {
        b.Navigation("addresses");
      });
#pragma warning restore 612, 618
    }
  }
}