// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using api_my_bank_dotnet.Data;

namespace api_my_bank_dotnet.Migrations
{
  [DbContext(typeof(DataContext))]
  [Migration("20220114113355_bank_account")]
  partial class bank_account
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
        .HasAnnotation("Relational:MaxIdentifierLength", 64)
        .HasAnnotation("ProductVersion", "5.0.13");

      modelBuilder.Entity("api_my_bank_dotnet.Models.BankAccount", b =>
      {
        b.Property<ulong>("bank_account_id")
          .ValueGeneratedOnAdd()
          .HasColumnType("bigint unsigned");

        b.Property<uint>("branch_number")
          .HasColumnType("int unsigned");

        b.Property<ulong>("account_number")
          .HasColumnType("bigint unsigned");

        b.Property<string>("currency")
          .IsRequired()
          .HasMaxLength(20)
          .HasColumnType("varchar(20)");

        b.Property<ulong>("monthly_income")
          .HasColumnType("bigint unsigned");

        b.Property<DateTime>("created_at")
          .HasColumnType("datetime");

        b.HasKey("bank_account_id");

        b.HasIndex("account_number")
          .IsUnique();

        b.ToTable("bank_account");
      });
#pragma warning restore 612, 618
    }
  }
}